#!/bin/sh
set -e

if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
  deb-systemd-invoke stop lora-ttn.service >/dev/null
  systemctl disable lora-ttn.service || true
  rm /var/log/thingsplex/lora-ttn/* || true
fi